language: R
language: java

cache: packages
sudo: required

cran: http://cran.rstudio.com

r_binary_packages:
 - rgdal
 - rJava
 - xlsxjars
 
notifications:
  email:
    on_success: change
    on_failure: change
