language: r
sudo: required
cran: http://cran.rstudio.com
dist: trusty
r_binary_packages:
 - rJava
 - xlsxjars

before_install:
  - curl -OL https://raw.githubusercontent.com/metacran/r-builder/master/pkg-build.sh
  - chmod 755 pkg-build.sh
  - ./pkg-build.sh bootstrap
  - cd
  - wget http://download.osgeo.org/gdal/2.0.1/gdal-2.0.1.tar.gz
  - tar zxf gdal-2.0.1.tar.gz
  - cd gdal-2.0.1
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.2.tar.gz
  - tar zxvf proj-4.9.2.tar.gz
  - cd proj-4.9.2
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd /home/travis/build/adamdsmith/MABM
  
notifications:
  email:
    on_success: change
    on_failure: change
